name: Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./dist/reloop-beatmix.js ./res/ReloopBeatmix.midi.xml
          if-no-files-found: error
